#!C:/Users/bulld/AppData/Local/Programs/Python/Python39/python.exe

import re
import sys


commit_pattern = r'^\[[0-9]+\][а-яА-я]+'
msg = ''
with open(sys.argv[1], 'r') as os:
    msg = os.read()


if not re.match(commit_pattern, msg):
    print('Incorrect commit message [num]commit')
    sys.exit(-1)
